### ISSUE TITLE
无法打印日志

### ISSUE THREAD

**Issue by nobody2014100** [wuyinxian124/nettybook2#1]
无法打印日志啊，配置的log4j貌似并没有生效

![image](https://cloud.githubusercontent.com/assets/8716969/17961916/e01b9f90-6ae0-11e6-9fe2-2718c4b9ee75.png)

**Comment by nobody2014100** [comment]
原因是配置文件不在src下面，导致无法读取配置文件
![image](https://cloud.githubusercontent.com/assets/8716969/17965865/556a00ce-6af1-11e6-8d81-350ec4ec906d.png)

**Comment by yuanqixiang** [comment]
用IDEA打开此项目时，项目结构不对，导致读不到resources下面的log配置文件，更换一下project structures
![image](https://user-images.githubusercontent.com/23355890/56558067-fdab2c00-65cf-11e9-9eae-42033c0f0caa.png)
